CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

SHOW_FPS = True
PRINT_FPS = True
SHOW_CENTER_GUIDE = True
SHOW_GRID = True
SHOW_ROI = True
SHOW_STATUS_TEXT = True
CROSSHAIR_SIZE = 24
GRID_LINE_WIDTH = 1
ROI_SCALE_NUM = 4
ROI_SCALE_DEN = 5

WINDOW_TITLE = "TrackingCar Vision"
