CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

SHOW_FPS = True
PRINT_FPS = True
SHOW_CENTER_GUIDE = True
SHOW_GRID = True
SHOW_ROI = True
SHOW_STATUS_TEXT = True
CROSSHAIR_SIZE = 24
GRID_LINE_WIDTH = 1
ROI_SCALE_NUM = 4
ROI_SCALE_DEN = 5

ENABLE_TARGET_DETECT = True
TARGET_MODE = "auto"  # auto, circle, rect
TARGET_CIRCLE_THRESHOLD = 3000
TARGET_RECT_THRESHOLD = 10000
TARGET_MIN_RADIUS = 8
TARGET_MAX_RADIUS = 220
TARGET_MIN_RECT_W = 20
TARGET_MIN_RECT_H = 20
PRINT_TARGET = False

WINDOW_TITLE = "TrackingCar Vision"
