CAMERA_WIDTH = 512
CAMERA_HEIGHT = 320

SHOW_FPS = True
PRINT_FPS = True
SHOW_CENTER_GUIDE = True
SHOW_GRID = True
SHOW_ROI = True
SHOW_STATUS_TEXT = True
CROSSHAIR_SIZE = 24
GRID_LINE_WIDTH = 1
ROI_SCALE_NUM = 3
ROI_SCALE_DEN = 5

ENABLE_TARGET_DETECT = True
TARGET_MODE = "blob"  # blob, circle, rect, auto
TARGET_BLOB_THRESHOLDS = [[0, 45, -128, 127, -128, 127]]  # dark/black target
TARGET_BLOB_AREA_MIN = 80
TARGET_BLOB_PIXELS_MIN = 80
TARGET_BLOB_MIN_W = 6
TARGET_BLOB_MIN_H = 6
TARGET_BLOB_MAX_ASPECT_X100 = 350
TARGET_CIRCLE_THRESHOLD = 3000
TARGET_RECT_THRESHOLD = 10000
TARGET_MIN_RADIUS = 8
TARGET_MAX_RADIUS = 110
TARGET_MIN_RECT_W = 20
TARGET_MIN_RECT_H = 20
DETECT_EVERY_N_FRAMES = 1
TARGET_SMOOTHING_ALPHA_X100 = 35
TARGET_LOST_HOLD_FRAMES = 5
PRINT_TARGET = False

WINDOW_TITLE = "TrackingCar Vision"
