try:
    from config import (
        CONFIG_SOURCE,
        CONFIG_VERSION,
        CAMERA_HEIGHT,
        CAMERA_BUFFER_NUM,
        CAMERA_CONTRAST,
        CAMERA_EXPOSURE,
        CAMERA_FPS,
        CAMERA_GAIN,
        CAMERA_SKIP_FRAMES,
        CAMERA_WB_GAIN,
        CAMERA_WIDTH,
        CROSSHAIR_SIZE,
        DETECT_EVERY_N_FRAMES,
        ENABLE_TARGET_DETECT,
        ENABLE_UART_OUTPUT,
        GRID_LINE_WIDTH,
        ENABLE_LASER_DETECT,
        LASER_AREA_MAX,
        LASER_AREA_MIN,
        LASER_CENTER_METHOD,
        LASER_COLOR,
        LASER_CONFIRM_DISTANCE,
        LASER_CONFIRM_FRAMES,
        LASER_GREEN_THRESHOLDS,
        LASER_MAX_ELONGATION_X100,
        LASER_MAX_ASPECT_X100,
        LASER_MAX_H,
        LASER_MAX_W,
        LASER_MIN_H,
        LASER_MIN_ROUNDNESS_X100,
        LASER_MIN_W,
        LASER_PIXELS_MIN,
        LASER_JITTER_DISTANCE,
        LASER_JITTER_SMOOTHING_ALPHA_X100,
        LASER_RED_THRESHOLDS,
        LASER_FALLBACK_FULL_FRAME,
        LASER_BACKGROUND_CALIB_FRAMES,
        LASER_LOST_HOLD_FRAMES,
        LASER_MIN_DENSITY_X100,
        LASER_REFINE_CORE,
        LASER_REFINE_MARGIN,
        LASER_REQUIRE_TARGET,
        LASER_SCORE_MIN,
        LASER_STATIC_MIN_HITS,
        LASER_STATIC_REJECT_DISTANCE,
        LASER_STICK_DISTANCE,
        LASER_STICK_SCORE_MARGIN,
        LASER_USE_ROI,
        LASER_SMOOTHING_ALPHA_X100,
        LASER_SNAP_DISTANCE,
        LASER_TARGET_BONUS_DISTANCE,
        LASER_TARGET_BACKGROUND_CALIB_FRAMES,
        LASER_TARGET_ROI_MARGIN,
        LASER_TARGET_LOST_FALLBACK_FRAMES,
        LASER_TRACK_BONUS_DISTANCE,
        LASER_USE_BACKGROUND_CALIB,
        LASER_USE_TARGET_ROI,
        PRINT_FPS,
        PRINT_TIMING,
        TIMING_PRINT_EVERY_N_FRAMES,
        PRINT_LASER,
        PRINT_TARGET,
        ROI_SCALE_DEN,
        ROI_SCALE_NUM,
        SHOW_CENTER_GUIDE,
        SHOW_FPS,
        SHOW_GRID,
        SHOW_ROI,
        SHOW_STATUS_TEXT,
        SHOW_VERBOSE_STATUS,
        SHOW_TARGET_BOX,
        TARGET_BLOB_CENTER_METHOD,
        TARGET_MARKER_BOX_MAX_H,
        TARGET_MARKER_BOX_MAX_W,
        TARGET_MARKER_BOX_MIN_H,
        TARGET_MARKER_BOX_MIN_W,
        TARGET_MARKER_BOX_PADDING,
        TARGET_CIRCLE_THRESHOLD,
        TARGET_BLOB_AREA_MIN,
        TARGET_BLOB_MAX_ASPECT_X100,
        TARGET_BLOB_MIN_H,
        TARGET_BLOB_MIN_W,
        TARGET_BLOB_PIXELS_MIN,
        TARGET_BLOB_THRESHOLDS,
        TARGET_LOST_HOLD_FRAMES,
        TARGET_MAX_RADIUS,
        TARGET_MIN_RADIUS,
        TARGET_MIN_RECT_H,
        TARGET_MIN_RECT_W,
        TARGET_MODE,
        TARGET_FULL_SEARCH_EVERY_N_FRAMES,
        TARGET_PERSPECTIVE_FALLBACK_BLOB,
        TARGET_PERSPECTIVE_MAX_ASPECT_X100,
        TARGET_PERSPECTIVE_MIN_AREA,
        TARGET_PERSPECTIVE_MIN_H,
        TARGET_PERSPECTIVE_MIN_W,
        TARGET_RECT_BLOB_ROI_MARGIN,
        TARGET_RECT_USE_BLOB_ROI,
        TARGET_RECT_THRESHOLD,
        TARGET_CORNER_SMOOTHING_ALPHA_X100,
        TARGET_DETECT_EVERY_N_FRAMES_WHEN_LASER,
        TARGET_FREEZE_HOLD_FRAMES_AFTER_LASER,
        TARGET_FREEZE_WHEN_LASER,
        TARGET_SIZE_SMOOTHING_ALPHA_X100,
        TARGET_SMOOTH_MAX_JUMP,
        TARGET_SMOOTHING_ALPHA_X100,
        TARGET_TRACKING_ROI_MARGIN,
        TARGET_USE_TRACKING_ROI,
        UART_BAUDRATE,
        UART_PORT,
        UART_OUTPUT_MODE,
        UART_PRINT_ERRORS,
        UART_RX_FUNC,
        UART_RX_PIN,
        UART_SEND_EVERY_N_FRAMES,
        UART_TX_FUNC,
        UART_TX_PIN,
    )
except ImportError:
    CONFIG_VERSION = "2026-07-11-competition"
    CONFIG_SOURCE = "fallback-main"
    CAMERA_WIDTH = 512
    CAMERA_HEIGHT = 320
    CAMERA_FPS = 60
    CAMERA_BUFFER_NUM = 1
    CAMERA_SKIP_FRAMES = 5
    CAMERA_CONTRAST = -1
    CAMERA_EXPOSURE = 2800
    CAMERA_GAIN = 1
    CAMERA_WB_GAIN = []
    SHOW_FPS = True
    SHOW_VERBOSE_STATUS = False
    PRINT_FPS = False
    PRINT_TIMING = False
    TIMING_PRINT_EVERY_N_FRAMES = 60
    SHOW_CENTER_GUIDE = False
    SHOW_GRID = False
    SHOW_ROI = False
    SHOW_STATUS_TEXT = True
    SHOW_TARGET_BOX = True
    CROSSHAIR_SIZE = 24
    GRID_LINE_WIDTH = 1
    ENABLE_LASER_DETECT = True
    LASER_COLOR = "green"
    LASER_RED_THRESHOLDS = [[70, 100, 35, 127, -20, 127]]
    LASER_GREEN_THRESHOLDS = [
        [68, 100, -128, -10, -128, 127],
        [55, 100, -128, -4, -128, 127],
        [35, 100, -128, -12, -128, 127],
    ]
    LASER_CENTER_METHOD = "blob"
    LASER_USE_ROI = False
    LASER_AREA_MIN = 3
    LASER_AREA_MAX = 320
    LASER_PIXELS_MIN = 3
    LASER_MIN_W = 1
    LASER_MIN_H = 1
    LASER_MAX_W = 42
    LASER_MAX_H = 42
    LASER_MAX_ASPECT_X100 = 350
    LASER_CONFIRM_FRAMES = 1
    LASER_CONFIRM_DISTANCE = 28
    LASER_REQUIRE_TARGET = True
    LASER_FALLBACK_FULL_FRAME = False
    LASER_USE_TARGET_ROI = True
    LASER_TARGET_ROI_MARGIN = 48
    LASER_TARGET_LOST_FALLBACK_FRAMES = 0
    LASER_MIN_DENSITY_X100 = 12
    LASER_MIN_ROUNDNESS_X100 = 0
    LASER_MAX_ELONGATION_X100 = 100
    LASER_SCORE_MIN = 0
    LASER_REFINE_CORE = False
    LASER_REFINE_MARGIN = 6
    LASER_USE_BACKGROUND_CALIB = True
    LASER_BACKGROUND_CALIB_FRAMES = 25
    LASER_TARGET_BACKGROUND_CALIB_FRAMES = 15
    LASER_STATIC_REJECT_DISTANCE = 18
    LASER_STATIC_MIN_HITS = 3
    LASER_TRACK_BONUS_DISTANCE = 45
    LASER_STICK_DISTANCE = 0
    LASER_STICK_SCORE_MARGIN = 0
    LASER_TARGET_BONUS_DISTANCE = 0
    LASER_SMOOTHING_ALPHA_X100 = 100
    LASER_JITTER_DISTANCE = 0
    LASER_JITTER_SMOOTHING_ALPHA_X100 = 100
    LASER_SNAP_DISTANCE = 80
    LASER_LOST_HOLD_FRAMES = 2
    PRINT_LASER = False
    ROI_SCALE_NUM = 9
    ROI_SCALE_DEN = 10
    TARGET_MARKER_BOX_MIN_W = 0
    TARGET_MARKER_BOX_MIN_H = 0
    TARGET_MARKER_BOX_PADDING = 4
    TARGET_MARKER_BOX_MAX_W = 220
    TARGET_MARKER_BOX_MAX_H = 170
    ENABLE_TARGET_DETECT = True
    TARGET_MODE = "perspective"
    TARGET_USE_TRACKING_ROI = True
    TARGET_TRACKING_ROI_MARGIN = 64
    TARGET_FULL_SEARCH_EVERY_N_FRAMES = 12
    TARGET_RECT_USE_BLOB_ROI = True
    TARGET_RECT_BLOB_ROI_MARGIN = 18
    TARGET_PERSPECTIVE_FALLBACK_BLOB = True
    TARGET_PERSPECTIVE_MIN_W = 40
    TARGET_PERSPECTIVE_MIN_H = 30
    TARGET_PERSPECTIVE_MIN_AREA = 1200
    TARGET_PERSPECTIVE_MAX_ASPECT_X100 = 450
    TARGET_BLOB_CENTER_METHOD = "rect"
    TARGET_BLOB_THRESHOLDS = [[0, 45, -128, 127, -128, 127]]
    TARGET_BLOB_AREA_MIN = 80
    TARGET_BLOB_PIXELS_MIN = 80
    TARGET_BLOB_MIN_W = 6
    TARGET_BLOB_MIN_H = 6
    TARGET_BLOB_MAX_ASPECT_X100 = 350
    TARGET_SMOOTH_MAX_JUMP = 80
    TARGET_SMOOTHING_ALPHA_X100 = 75
    TARGET_CORNER_SMOOTHING_ALPHA_X100 = 45
    TARGET_SIZE_SMOOTHING_ALPHA_X100 = 45
    TARGET_LOST_HOLD_FRAMES = 3
    TARGET_CIRCLE_THRESHOLD = 3000
    TARGET_RECT_THRESHOLD = 10000
    TARGET_MIN_RADIUS = 8
    TARGET_MAX_RADIUS = 110
    TARGET_MIN_RECT_W = 20
    TARGET_MIN_RECT_H = 20
    DETECT_EVERY_N_FRAMES = 1
    TARGET_DETECT_EVERY_N_FRAMES_WHEN_LASER = 1
    TARGET_FREEZE_WHEN_LASER = False
    TARGET_FREEZE_HOLD_FRAMES_AFTER_LASER = 0
    PRINT_TARGET = False
    ENABLE_UART_OUTPUT = False
    UART_PORT = "/dev/ttyS1"
    UART_BAUDRATE = 115200
    UART_TX_PIN = "A19"
    UART_RX_PIN = "A18"
    UART_TX_FUNC = "UART1_TX"
    UART_RX_FUNC = "UART1_RX"
    UART_OUTPUT_MODE = "aim"
    UART_SEND_EVERY_N_FRAMES = 2
    UART_PRINT_ERRORS = True
