/**
 * @file actuator_validation_config.h
 * @brief FreeRTOS 执行机构组合验证参数。
 */
#ifndef ACTUATOR_VALIDATION_CONFIG_H
#define ACTUATOR_VALIDATION_CONFIG_H

#define ACTUATOR_VALIDATION_ENABLED             0

#define ACTUATOR_VALIDATION_START_DELAY_MS      3000U
#define ACTUATOR_VALIDATION_ENABLE_DELAY_MS      200U
#define ACTUATOR_VALIDATION_STAGE_RUN_MS         1500U
#define ACTUATOR_VALIDATION_INTER_STAGE_DELAY_MS 1500U
#define ACTUATOR_VALIDATION_POLL_PERIOD_MS         10U
#define ACTUATOR_VALIDATION_FINAL_HOLD_MS         3000U

#define ACTUATOR_VALIDATION_WHEEL_SPEED_MM_S     250.0f
#define ACTUATOR_VALIDATION_STEPPER_SPEED_RPM     30U
#define ACTUATOR_VALIDATION_STEPPER_ACCELERATION  10U
#define ACTUATOR_VALIDATION_STEPPER_PULSES        800U

#endif /* ACTUATOR_VALIDATION_CONFIG_H */
