APP_VERSION = "0.9.1-mspm0-link"

# Balanced real-time profile: lower CV workload while retaining enough target detail.
CAMERA_WIDTH = 320
CAMERA_HEIGHT = 240
CAMERA_FPS = 60
CAMERA_BUFFER_NUM = 1
CAMERA_EXPOSURE = 2800
CAMERA_GAIN = 1
CAMERA_WB_GAIN = [0.134, 0.0625, 0.0625, 0.1239]
CAMERA_WARMUP_FRAMES = 30
CAMERA_BENCHMARK_CANDIDATES = [(320, 240, 60), (512, 320, 60), (448, 448, 60)]
CAMERA_BENCHMARK_INDEX = 0
CAMERA_BENCHMARK_SAMPLE_FRAMES = 300
UART_TEST_SEND_EVERY_N_FRAMES = 6
UART_TEST_FRAME = "AIM,0,0,0,0,0,0,0,LOST,LOST\n"

UART_PORT = "/dev/ttyS0"
UART_BAUDRATE = 115200
UART_TX_PIN = "A16"
UART_RX_PIN = "A17"
UART_TX_FUNC = "UART0_TX"
UART_RX_FUNC = "UART0_RX"
UART_REQUIRE_COMM_NONE = True
# Full-duplex bench link: A16 is TX and A17 is RX. AIM transmission never
# waits for a reply, so an unplugged MSPM0 cannot stall the vision pipeline.
UART_ENABLE_RX = True
UART_RX_POLL_EVERY_N_FRAMES = 6
MSPM0_READY_PREFIX = "MSPM0,READY"
# Keep ASCII compatibility until MSPM0 binary parser passes hardware acceptance.
UART_PROTOCOL_MODE = "ascii_aim"
BINARY_PROTOCOL_VERSION = 1
BINARY_ALLOW_PREDICTED = False

# Dimensionless reference values used only by the visual aspect-ratio filter.
# They are not physical calibration; real millimetre dimensions belong in PLANE_*_MM.
TARGET_ASPECT_WIDTH_REF = 174.0
TARGET_ASPECT_HEIGHT_REF = 261.0
# Deprecated compatibility aliases for older settings consumers.
TARGET_WHITE_WIDTH_MM = TARGET_ASPECT_WIDTH_REF
TARGET_WHITE_HEIGHT_MM = TARGET_ASPECT_HEIGHT_REF
TARGET_OUTER_WIDTH_MM = 210.0
TARGET_OUTER_HEIGHT_MM = 297.0
TARGET_CIRCLE_RADIUS_MM = 60.0

# Fill these with ruler measurements of the finished target before enabling millimetre mapping.
PLANE_WHITE_WIDTH_MM = None
PLANE_WHITE_HEIGHT_MM = None
PLANE_OUTER_WIDTH_MM = None
PLANE_OUTER_HEIGHT_MM = None
PLANE_CIRCLE_RADIUS_MM = 60.0
PLANE_CIRCLE_POINT_COUNT = 50
PLANE_CACHE_CORNER_EPSILON_PX = 0.75

TARGET_REFINE_GAUSSIAN_SIZE = 3
TARGET_REFINE_ADAPTIVE_BLOCK_SIZE = 15
TARGET_REFINE_ADAPTIVE_C = 5
TARGET_REFINE_APPROX_EPSILON_RATIO = 0.02
TARGET_REFINE_MIN_AREA_RATIO = 0.01
TARGET_REFINE_MIN_AREA_PX = 64
TARGET_REFINE_MAX_ASPECT_ERROR = 0.45
TARGET_REFINE_MIN_ANGLE_DEG = 45.0
TARGET_REFINE_MAX_ANGLE_DEG = 135.0

ROI_MARGIN_MIN_PX = 32
ROI_MARGIN_RATIO = 0.35
ROI_FAIL_TO_GLOBAL_FRAMES = 3
GLOBAL_PROPOSAL_WIDTH = 320
GLOBAL_PROPOSAL_BLACK_THRESHOLD = 100
GLOBAL_PROPOSAL_MIN_AREA_RATIO = 0.003
GLOBAL_PROPOSAL_MAX_ASPECT_ERROR = 0.55

TARGET_CONFIRM_ACQUIRE_FRAMES = 3
TARGET_CONFIRM_RETRACK_FRAMES = 2
TARGET_LOWPASS_ALPHA = 0.75
TARGET_OUTLIER_JUMP_MIN_PX = 28
TARGET_OUTLIER_JUMP_RATIO = 0.50
TARGET_ENABLE_KALMAN = True
# High Q is intentional: locked tracking follows motion quickly; the low-pass stage supplies smoothing.
TARGET_KALMAN_PROCESS_NOISE = 1000.0
TARGET_KALMAN_MEASUREMENT_NOISE = 9.0
# Visual prediction may remain on screen longer; UART control is still capped by MSPM0_STALE_MS.
PREDICT_HOLD_MS = 120
PREDICT_MAX_FRAMES = 5

LASER_LAB_LOWER = (45, 160, 0)
LASER_LAB_UPPER = (230, 255, 115)
LASER_MIN_AREA = 2
LASER_MAX_AREA = 120
LASER_MIN_CIRCULARITY = 0.45
LASER_MIN_DENSITY = 0.45
LASER_CONFIRM_FRAMES = 2
LASER_RELOCK_RADIUS = 8
LASER_BACKGROUND_MATCH_RADIUS = 8
LASER_BACKGROUND_REQUIRED_FRAMES = 25
LASER_JUMP_MIN_PX = 12
LASER_JUMP_RATIO = 0.30

# Authoritative UART measurement freshness. Keep at or below the MSPM0 watchdog limit.
MSPM0_STALE_MS = 100
MSPM0_WATCHDOG_MS = 100
ENABLE_DEBUG_DRAW = True
DISPLAY_VERBOSE_STATUS = False
ENABLE_TIMING = True
PIPELINE_TIMING_WINDOW = 120
PERFORMANCE_SNAPSHOT_INTERVAL = 10
PIPELINE_TARGET_P95_BUDGET_US = 12000
PIPELINE_BENCHMARK_SAMPLE_FRAMES = 300
